// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDKLd7BaYFy0h03afnw683eTEqEURGD-U',
    appId: '1:49765240668:web:c5c150eddd117afbefbb99',
    messagingSenderId: '49765240668',
    projectId: 'todo-app-fbe9c',
    authDomain: 'todo-app-fbe9c.firebaseapp.com',
    storageBucket: 'todo-app-fbe9c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOgIR0dU3L4imOLBZx7OOnpzv8izPwEOE',
    appId: '1:49765240668:android:4f889c3f582d3227efbb99',
    messagingSenderId: '49765240668',
    projectId: 'todo-app-fbe9c',
    storageBucket: 'todo-app-fbe9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDph-UKF0JayLA7Ihj4_xdJ5qF2kJbINI',
    appId: '1:49765240668:ios:b752e9e999ba4f61efbb99',
    messagingSenderId: '49765240668',
    projectId: 'todo-app-fbe9c',
    storageBucket: 'todo-app-fbe9c.firebasestorage.app',
    androidClientId: '49765240668-poit770av2a9erga6aptoh835u8jlh3o.apps.googleusercontent.com',
    iosClientId: '49765240668-lj9d9ltdhgvcvp75hu8e52abtt37cba0.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDph-UKF0JayLA7Ihj4_xdJ5qF2kJbINI',
    appId: '1:49765240668:ios:b752e9e999ba4f61efbb99',
    messagingSenderId: '49765240668',
    projectId: 'todo-app-fbe9c',
    storageBucket: 'todo-app-fbe9c.firebasestorage.app',
    androidClientId: '49765240668-poit770av2a9erga6aptoh835u8jlh3o.apps.googleusercontent.com',
    iosClientId: '49765240668-lj9d9ltdhgvcvp75hu8e52abtt37cba0.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDKLd7BaYFy0h03afnw683eTEqEURGD-U',
    appId: '1:49765240668:web:e5371dde33aa9b2fefbb99',
    messagingSenderId: '49765240668',
    projectId: 'todo-app-fbe9c',
    authDomain: 'todo-app-fbe9c.firebaseapp.com',
    storageBucket: 'todo-app-fbe9c.firebasestorage.app',
  );
}
